// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo9YkEWSO_uTjmj98R8nlBLpXa-rVH92I',
    appId: '1:1096692682125:web:f4b48690de747413cc81c4',
    messagingSenderId: '1096692682125',
    projectId: 'fir-task-8641c',
    authDomain: 'fir-task-8641c.firebaseapp.com',
    storageBucket: 'fir-task-8641c.appspot.com',
    measurementId: 'G-TMC55853BN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqhpQ-fRj4pi7mUjkSU7o1YJwiHWZ7XaI',
    appId: '1:1096692682125:android:04c493cc7e4f0ffccc81c4',
    messagingSenderId: '1096692682125',
    projectId: 'fir-task-8641c',
    storageBucket: 'fir-task-8641c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9-e_MwJn5evRafmqr6L9tJn_Y_5JmmDc',
    appId: '1:1096692682125:ios:e6257864e50653f9cc81c4',
    messagingSenderId: '1096692682125',
    projectId: 'fir-task-8641c',
    storageBucket: 'fir-task-8641c.appspot.com',
    iosBundleId: 'com.example.listProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9-e_MwJn5evRafmqr6L9tJn_Y_5JmmDc',
    appId: '1:1096692682125:ios:e5d7bc2b02161c50cc81c4',
    messagingSenderId: '1096692682125',
    projectId: 'fir-task-8641c',
    storageBucket: 'fir-task-8641c.appspot.com',
    iosBundleId: 'com.example.listProjects.RunnerTests',
  );
}
